name: igleadboard_core
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  archive: ^3.6.0
  args: ^2.4.2

dev_dependencies:
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
